DELETE FROM `weenie` WHERE `class_Id` = 1910166;

INSERT INTO `weenie` (`class_Id`, `class_Name`, `type`, `last_Modified`)
VALUES (1910166, 'ace1910166-ravenaegis', 1, '2019-05-03 00:00:00') /* Generic */;

INSERT INTO `weenie_properties_int` (`object_Id`, `type`, `value`)
VALUES (1910166,   1,          2) /* ItemType - Armor */
     , (1910166,   3,          9) /* PaletteTemplate - Grey */
     , (1910166,   5,        600) /* EncumbranceVal */
     , (1910166,   9,    2097152) /* ValidLocations - Shield */
     , (1910166,  16,          1) /* ItemUseable - No */
     , (1910166,  18,         32) /* UiEffects - Fire */
     , (1910166,  19,        10) /* Value */
     , (1910166,  28,          0) /* ArmorLevel */
     , (1910166,  33,          1) /* Bonded - Bonded */
     , (1910166,  36,       9999) /* ResistMagic */
     , (1910166,  51,          4) /* CombatUse - Shield */
     , (1910166,  52,          3) /* ParentLocation - Shield */
     , (1910166,  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */
     , (1910166, 106,        350) /* ItemSpellcraft */
     , (1910166, 107,       3000) /* ItemCurMana */
     , (1910166, 108,       3000) /* ItemMaxMana */
     , (1910166, 114,          1) /* Attuned - Attuned */
     , (1910166, 115,        400) /* ItemSkillLevelLimit */
     , (1910166, 151,          2) /* HookType - Wall */
     , (1910166, 158,          7) /* WieldRequirements - Level */
     , (1910166, 159,          1) /* WieldSkillType - Axe */
     , (1910166, 160,        100) /* WieldDifficulty */
     , (1910166, 179,  536870912) /* ImbuedEffect - IgnoreSomeMagicProjectileDamage */;

INSERT INTO `weenie_properties_bool` (`object_Id`, `type`, `value`)
VALUES (1910166,  11, True ) /* IgnoreCollisions */
     , (1910166,  13, True ) /* Ethereal */
     , (1910166,  14, True ) /* GravityStatus */
     , (1910166,  19, True ) /* Attackable */
     , (1910166,  22, True ) /* Inscribable */
     , (1910166,  69, False) /* IsSellable */
     , (1910166,  99, True ) /* Ivoryable */;

INSERT INTO `weenie_properties_float` (`object_Id`, `type`, `value`)
VALUES (1910166,   5, -0.025000000372529) /* ManaRate */
     , (1910166,  13,       0) /* ArmorModVsSlash */
     , (1910166,  14,       0) /* ArmorModVsPierce */
     , (1910166,  15,       0) /* ArmorModVsBludgeon */
     , (1910166,  16,       0) /* ArmorModVsCold */
     , (1910166,  17,       0) /* ArmorModVsFire */
     , (1910166,  18,       0) /* ArmorModVsAcid */
     , (1910166,  19,       0) /* ArmorModVsElectric */
     , (1910166, 159,    0.25) /* AbsorbMagicDamage */;

INSERT INTO `weenie_properties_string` (`object_Id`, `type`, `value`)
VALUES (1910166,   1, 'Raven Aegis') /* Name */
     , (1910166,  16, 'A magically imbued Aegis crafted by the Order of the Raven Hand.  Although the Aegis provides no physical protection, the aura generated by the shield will negate a portion of all magical projectile attacks, based upon the wielder''s abilities.') /* LongDesc */;

INSERT INTO `weenie_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (1910166,   1,   33559617) /* Setup */
     , (1910166,   3,  536870932) /* SoundTable */
     , (1910166,   7,  268437527) /* ClothingBase */
     , (1910166,   8,  100687958) /* Icon */
     , (1910166,  22,  872415275) /* PhysicsEffectTable */;

INSERT INTO `weenie_properties_spell_book` (`object_Id`, `spell`, `probability`)
VALUES (1910166,   249,      2)  /* Invulnerability Self VI */
     , (1910166,  3819,      2)  /* Conscript's Might */
     , (1910166,  3820,      2)  /* Conscript's Ward */;
